language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean scalafmtTest coverage test coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

after_success:
 - bash <(curl -s https://codecov.io/bash)
