version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:9
    steps:
      - checkout
      - run: sbt ";reload plugins; sbt:scalafmt::test; scalafmt::test; reload return; sbt:scalafmt::test; scalafmt::test; test:scalafmt::test"
      - run: sbt ";coverage; test; coverageReport"
      - run: bash <(curl -s https://codecov.io/bash)
